# this page including the format of the messages
SPLIT_TYPE_AND_DATA_CHAR = '@'
START_CONNECTION_MESSAGE = 'start'
JOIN_TO_ROOM_REQUEST_SIGN = 'join'
EXIT_SIGN = 'exit'
CREATE_NEW_ROOM_SIGN = 'create'
SEND_MESSAGE_TO_REST_USERS_IN_ROOM_SIGN = 'send'
SUCCESS_MESSAGE = 'success'
USERNAME_IS_ALREADY_EXISTS_MESSAGE = 'failed_username'
FAILED_MESSAGE = 'failed'
START_CONNECTION_MESSAGE = 'start'
PORT = 3337
